### ISSUE TITLE
Data persistence question

### ISSUE THREAD

**Issue by ianshefferman** [bprodoehl/docker-scumblr#1]
First off, thank you for making this excellent container. It's much more convenient than the manual installation process.

I'm pretty new to Docker and am wondering what sort of workflow I should use for stopping/starting/restarting scumblr and scumblr-mysql while persisting everything in the database.

launch-scumblr.sh appears to delete each container and starts over from a clean slate, removing everything in the database in the process.

How can I modify the script (or write a new one) to just handle regular starting and stopping without affecting the database?

Thanks.

**Comment by ianshefferman** [comment]
I resolved this. The issue was partly due to me failing to read the entire README.

For anyone interested, here is what I modified in `launch-scumblr.sh` to make the data persistent:
1. Created directory `/opt/scumblr-mysql`and added the following line to the `docker run` command for `scumblr-mysql`:
   
     `-v /opt/scumblr-mysql:/var/lib/mysql \`
2. Set the following environment variables to `false` after running the container for the first time:
- SCUMBLR_CREATE_DB
- SCUMBLR_LOAD_SCHEMA
- SCUMBLR_RUN_MIGRATIONS
- SCUMBLR_SEED_STATUSES
- SCUMBLR_SEED_DB
- SCUMBLR_SEED_ADMIN
- SKETCHY_CREATE_DB

**Comment by bprodoehl** [comment]
Sorry for the late reply on this, and I'm glad you were able to solve your problem in the meantime.  Yes, what you're saying above sounds right.  You should also be able to just omit those environment variables from subsequent runs.  I usually have a relaunch script, but I see I didn't check one in.  That's an important bit, so I'll get that in as soon as I have some time to run through and really test it out.

**Comment by ianshefferman** [comment]
No problem. I'd certainly make use of the official relaunch script once you publish it.
